name: playmaker1710 run outside

  on:
    push:
      branches:
        - master

  jobs:
    instauto:
      runs-on: ubuntu-latest

      steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: git clone https://github.com/idembele70/instaauto/
      - run: cd instauto
      - run: chmod +x stop_node_playmaker1710.sh
      - run: ./stop_node_playmaker1710.sh